# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node Continuous Integration

on:
  push:
    branches: [ testing ]
  pull_request:
    branches: [ master ]

jobs:
    test_pull_request:
        runs-on: windows-latest
        strategy:
          matrix:
            node-version: [10.x, 12.x]
        steps:
          - uses: actions/checkout@v2
          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v1
            with:
              node-version: ${{ matrix.node-version }}
          - run: npm ci //npm install
          - run: npm test -if-present
          - run: npm run build -if-present
